### ISSUE TITLE
Add @samus-aran (Ashley Nicolson) to Maintainers group

### ISSUE THREAD

**Issue by quaid** [theopensourceway/theproject#10]
I'm proposing we add @samus-aran (Ashley Nicolson) to the Maintainers group for the TOSW project.

This is in recognition of her contributions and ongoing activity, as well as interest in being an active member and leader in this growing community. We're a relatively young project, and in that time Ashley's efforts include:

* Made significant contributions to modernize the guidebook outline, with her insight and activity bringing TOSW guidance forward a decade;
* Followed through to author a key chapter in that modernization;
* Offered expertise and guidance across the project in how we use GitHub; and
* Collaborated on the organically growing architecture of this community from process to governance.

We of course do not have a formal governance that covers things such as what a Maintainer means (outside of a set of permissions in GitHub) and how we go about promoting someone to Maintainer. Thus we are both creating process, defining governance, and asking one of our friends and colleagues to take a more formal leadership role in this community.

Seems reasonable that we get +1 from each existing maintainer, tagged thusly:

@shaunix
@semioticrobotic +1 (enthusiastically plused)
@bproffitt
@quaid +1

**Comment by bproffitt** [comment]
+1 from me

**Comment by shaunix** [comment]
+1 from me too. Looks unanimous.

**Comment by quaid** [comment]
OK, I'll make it so!

**Comment by samus-aran** [comment]
Apologies on arriving late to the party (now closed :rofl: ) but thank you all for your support and although I have been absent the past week+ due to work commitment I'm eager to contribute and help support the project :+1:  Look forward to working together ^_^
