### ISSUE TITLE
2.0 Release announcement

### ISSUE THREAD

**Issue by quaid** [theopensourceway/theproject#58]
Announce the guidebook and why readers should care.

Secondary purpose is to introduce the community and invite participation, perhaps hint at upcoming stuff.

Should point to all relevant locations:

HTML (single page, multi-page if we have it)
PDF
EPub (if we have it)
GitHub repo
Main website
Main discussion forum

Use our own chapter on how to do a software release for any other ideas for this content:

https://github.com/theopensourceway/guidebook/blob/master/announcing_software_releases.adoc

**Comment by semioticrobotic** [comment]
I can draft something for @quaid review. Do you have a deadline in mind?

**Comment by semioticrobotic** [comment]
Getting this rolling. Feedback and edits welcome.

---

The Open Source Way community [1] is pleased to announce the latest release of the Open Source Way guidebook.

Written by practitioners from several organizations, the Open Source Way guidebook collects best practices for catalyzing, supporting, managing, and sustaining open source communities. This release (v 2.0) is licensed via XXX.

The guidebook is now available in various formats at the following locations:

HTML: https://www.theopensourceway.org/the_open_source_way-guidebook-2.0.html
PDF: https://www.theopensourceway.org/the_open_source_way-guidebook-2.0.pdf

The Open Source Way is an upstream community of open source practitioners who cultivate and curate best practices around community management. The project is always seeking contributions. For more details—and to get involved—please visit <https://github.com/theopensourceway/>.

---

[1] https://www.theopensourceway.org/

**Comment by quaid** [comment]
Thanks, merged in and working with the above text plus the [project's template/chapter in the guidebook](https://github.com/theopensourceway/guidebook/blob/main/announcing_software_releases.adoc).

This is the source for the debut announcement: https://github.com/theopensourceway/theproject/blob/main/marketing/2.0-debut-announcement.txt

**Comment by quaid** [comment]
@semioticrobotic the next version of the draft is ready for your review:

https://github.com/theopensourceway/theproject/blob/main/marketing/2.0-debut-announcement.txt

**Comment by quaid** [comment]
This is great, I love what you did, it's super-coherent now. I fixed a few wee typos, I think this one is ready to send. I'm going to plan it for Monday.
